export const tableData = [
    {
      invoice: "INV001",
      date: '7/2/2024',
      remark: 'T-shirt',
      paymentStatus: "Paid",
      amount: "250.00",
      account: '017**',
      paymentMethod: "Credit Card",
    },
    {
      invoice: "INV002",
      date: '7/2/2024',
      remark: 'T-shirt',
      paymentStatus: "Pending",
      amount: "150.00",
      account: '017**',
      paymentMethod: "PayPal",
    },
    {
      invoice: "INV003",
      date: '7/2/2024',
      remark: 'T-shirt',
      paymentStatus: "Unpaid",
      amount: "350.00",
      account: '017**',
      paymentMethod: "Bank Transfer",
    },
    {
      invoice: "INV004",
      date: '7/2/2024',
      remark: 'T-shirt',
      paymentStatus: "Paid",
      amount: "450.00",
      account: '017**',
      paymentMethod: "Credit Card",
    },
    {
      invoice: "INV005",
      date: '7/2/2024',
      remark: 'Bag',
      paymentStatus: "Paid",
      amount: "550.00",
      account: '017**',
      paymentMethod: "PayPal",
    },
    {
      invoice: "INV006",
      date: '7/2/2024',
      remark: 'T-shirt',
      paymentStatus: "Pending",
      amount: "200.00",
      account: '017**',
      paymentMethod: "Bank Transfer",
    },
    {
      invoice: "INV007",
      date: '7/2/2024',
      remark: 'Shoes',
      paymentStatus: "Unpaid",
      amount: "300.00",
      account: '017**',
      paymentMethod: "Credit Card",
    },
  ]